name: causal-nlp-extraction
channels:
  - conda-forge
dependencies:
  - bzip2
  - ca-certificates
  - libexpat
  - libffi
  - liblzma
  - libsqlite
  - libzlib
  - ncurses
  - openssl
  - pip
  - python=3.11.14
  - readline
  - setuptools
  - tk
  - wheel
  - pip:
      - transformers
      - torch
      - accelerate
      - langchain
      - langchain-community
      - langchain-core
      - langchain-openai
      - openai
      - sentence-transformers
      - sentencepiece
      - huggingface-hub
      - tiktoken
      - pypdf
      - nltk
      - RapidFuzz
      - gradio
      - fastapi
      - uvicorn
      - neo4j
      - pydantic
      - python-dotenv
      - dowhy
      - econml
      - pgmpy
      - gcastle
      - pywhy-graphs
      - lingam
      - tigramite
      - pygam
      - momentchi2
      - numdifftools
      - graphviz
      - pytorch-lightning
      - requests
      - pytz
      - PyYAML
